### ISSUE TITLE
ChannelTabs Issue: It's not working anymore.

### ISSUE THREAD

**Issue by marmoris-x** [samfundev/BetterDiscordStuff#10] opened 2024-09-20 02:09 UTC
_**Before you submit an issue please restart your discord. If the issue is still there feel free to write a bug report.**_

I have deleted the config file and the plugin file and downloaded them again from the betterdiscord website. But it is no longer loaded.

Please fix it 😭

**Comment by piemantr** [comment] 2024-09-20 05:31
I've tested this as well. Couldn't get ChannelTabs to open. I opened my recycling bin and found the config file with _new_[long string number], restored it, and I could use ChannelTabs again, with a caveat: it only shows the channel as Friends (or DMs, or the Shop and Store). And opening a new tab only opens another Friends tab and going back to the other tab takes you back to Friend.

At least I still have my bookmarked channels, but the Tabs feature isn't working.

**Comment by fowlis** [comment] 2024-09-20 13:13
Duplicate of https://github.com/samfundev/BetterDiscordStuff/issues/5

**Comment by marmoris-x** [comment] 2024-09-20 14:46
> Duplicate of #5

Idk, but for a week ago the plugin was still working

**Comment by wstirl** [comment] 2024-09-21 08:35
can confirm it doesn't work anymore

**Closed** 2024-10-06 16:37 UTC
Labels: bug
